//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DmsWebservice
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DmsWebservice.HOEnquirySoap")]
    public interface HOEnquirySoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveHOEnquiry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> SaveHOEnquiryAsync(string Enquirydata, string UserID, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLeadStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DmsWebservice.LeadStatusDO[]> GetLeadStatusAsync(string FromDate, string Todate, string Dealer_id, string InternetEnquiryID, string UserID, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDropoutLeads", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DmsWebservice.DropoutDO[]> GetDropoutLeadsAsync(string FromDate, string Todate, string UserID, string Password);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LeadStatusDO
    {
        
        private string sTATUSField;
        
        private string dEALER_IDField;
        
        private string iNVOICE_IDField;
        
        private string iNVOICE_DATEField;
        
        private string iNVOICE_STATUSField;
        
        private string bOOKING_IDField;
        
        private string bOOKING_DATEField;
        
        private string bOOKING_STATUSField;
        
        private string eNQ_FOLLOWUP_IDField;
        
        private string fOLLOWUP_DATEField;
        
        private string fOLLOWUP_REMARKSField;
        
        private string fOLLOWUP_STATUSField;
        
        private string dMS_ENQUIRY_IDField;
        
        private string dMS_ENQUIRY_DATEField;
        
        private string iNTERNET_ENQUIRY_IDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string STATUS
        {
            get
            {
                return this.sTATUSField;
            }
            set
            {
                this.sTATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DEALER_ID
        {
            get
            {
                return this.dEALER_IDField;
            }
            set
            {
                this.dEALER_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string INVOICE_ID
        {
            get
            {
                return this.iNVOICE_IDField;
            }
            set
            {
                this.iNVOICE_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string INVOICE_DATE
        {
            get
            {
                return this.iNVOICE_DATEField;
            }
            set
            {
                this.iNVOICE_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string INVOICE_STATUS
        {
            get
            {
                return this.iNVOICE_STATUSField;
            }
            set
            {
                this.iNVOICE_STATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string BOOKING_ID
        {
            get
            {
                return this.bOOKING_IDField;
            }
            set
            {
                this.bOOKING_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string BOOKING_DATE
        {
            get
            {
                return this.bOOKING_DATEField;
            }
            set
            {
                this.bOOKING_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string BOOKING_STATUS
        {
            get
            {
                return this.bOOKING_STATUSField;
            }
            set
            {
                this.bOOKING_STATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ENQ_FOLLOWUP_ID
        {
            get
            {
                return this.eNQ_FOLLOWUP_IDField;
            }
            set
            {
                this.eNQ_FOLLOWUP_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string FOLLOWUP_DATE
        {
            get
            {
                return this.fOLLOWUP_DATEField;
            }
            set
            {
                this.fOLLOWUP_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string FOLLOWUP_REMARKS
        {
            get
            {
                return this.fOLLOWUP_REMARKSField;
            }
            set
            {
                this.fOLLOWUP_REMARKSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string FOLLOWUP_STATUS
        {
            get
            {
                return this.fOLLOWUP_STATUSField;
            }
            set
            {
                this.fOLLOWUP_STATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string DMS_ENQUIRY_ID
        {
            get
            {
                return this.dMS_ENQUIRY_IDField;
            }
            set
            {
                this.dMS_ENQUIRY_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string DMS_ENQUIRY_DATE
        {
            get
            {
                return this.dMS_ENQUIRY_DATEField;
            }
            set
            {
                this.dMS_ENQUIRY_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string INTERNET_ENQUIRY_ID
        {
            get
            {
                return this.iNTERNET_ENQUIRY_IDField;
            }
            set
            {
                this.iNTERNET_ENQUIRY_IDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DropoutDO
    {
        
        private string dEALER_IDField;
        
        private string iNTERNET_ENQUIRY_IDField;
        
        private string rEASONField;
        
        private string cUSTOMER_NAMEField;
        
        private string aREAField;
        
        private string cITYField;
        
        private string sTATE_IDField;
        
        private string mOBILE_NUMBERField;
        
        private string eNQUIRY_DATEField;
        
        private string cREATED_ONField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DEALER_ID
        {
            get
            {
                return this.dEALER_IDField;
            }
            set
            {
                this.dEALER_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string INTERNET_ENQUIRY_ID
        {
            get
            {
                return this.iNTERNET_ENQUIRY_IDField;
            }
            set
            {
                this.iNTERNET_ENQUIRY_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string REASON
        {
            get
            {
                return this.rEASONField;
            }
            set
            {
                this.rEASONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CUSTOMER_NAME
        {
            get
            {
                return this.cUSTOMER_NAMEField;
            }
            set
            {
                this.cUSTOMER_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AREA
        {
            get
            {
                return this.aREAField;
            }
            set
            {
                this.aREAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CITY
        {
            get
            {
                return this.cITYField;
            }
            set
            {
                this.cITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string STATE_ID
        {
            get
            {
                return this.sTATE_IDField;
            }
            set
            {
                this.sTATE_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string MOBILE_NUMBER
        {
            get
            {
                return this.mOBILE_NUMBERField;
            }
            set
            {
                this.mOBILE_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ENQUIRY_DATE
        {
            get
            {
                return this.eNQUIRY_DATEField;
            }
            set
            {
                this.eNQUIRY_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string CREATED_ON
        {
            get
            {
                return this.cREATED_ONField;
            }
            set
            {
                this.cREATED_ONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface HOEnquirySoapChannel : DmsWebservice.HOEnquirySoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class HOEnquirySoapClient : System.ServiceModel.ClientBase<DmsWebservice.HOEnquirySoap>, DmsWebservice.HOEnquirySoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public HOEnquirySoapClient(EndpointConfiguration endpointConfiguration) : 
                base(HOEnquirySoapClient.GetBindingForEndpoint(endpointConfiguration), HOEnquirySoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HOEnquirySoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(HOEnquirySoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HOEnquirySoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(HOEnquirySoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HOEnquirySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> SaveHOEnquiryAsync(string Enquirydata, string UserID, string Password)
        {
            return base.Channel.SaveHOEnquiryAsync(Enquirydata, UserID, Password);
        }
        
        public System.Threading.Tasks.Task<DmsWebservice.LeadStatusDO[]> GetLeadStatusAsync(string FromDate, string Todate, string Dealer_id, string InternetEnquiryID, string UserID, string Password)
        {
            return base.Channel.GetLeadStatusAsync(FromDate, Todate, Dealer_id, InternetEnquiryID, UserID, Password);
        }
        
        public System.Threading.Tasks.Task<DmsWebservice.DropoutDO[]> GetDropoutLeadsAsync(string FromDate, string Todate, string UserID, string Password)
        {
            return base.Channel.GetDropoutLeadsAsync(FromDate, Todate, UserID, Password);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HOEnquirySoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.HOEnquirySoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HOEnquirySoap))
            {
                return new System.ServiceModel.EndpointAddress("https://www.advantagetvs.com/LeadIntegeration/HOEnquiry.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.HOEnquirySoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://www.advantagetvs.com/LeadIntegeration/HOEnquiry.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            HOEnquirySoap,
            
            HOEnquirySoap12,
        }
    }
}
